### ISSUE TITLE
Feature request\Help support on iterating over an array of objects

### ISSUE THREAD

**Issue by maxiride** [raphaelreyna/latte#12]
I'd like to use LATTE to generate some PDFs which include some tables with fixed headers but a dynamic number of rows.

Currently, the template substitution is 1 on 1, is there a way to repeat a block of code N times over a slice?

Is there anything you would suggest to look into to achieve this feature? I'm currently browsing for ways to iterate over data in latex but I doubt it's the best performant way.

**Comment by raphaelreyna** [comment]
Yeah, the templating for LaTTe supports iterating over arrays.
For example, if you wanted to create a document with a^n + b^n = c^n for multiple values of n you could use the `range` templating function.

The template would look like:
```
\documentclass{article}
\title{LaTTe Sample Document}
\begin{document}
\maketitle
Variations on the Pythagorean Theorem:
#! range .Exponents !#
$$ a ^ {#! . !#} + b ^ {#! . !#} = c ^ {#! . !#} $$
#! end !#
\end{document}
```

The API call:
```bash
curl -X POST -H "Content-Type: application/json" -d '{"template":"XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKIyEgcmFuZ2UgLkV4cG9uZW50cyAhIwokJCBhIF4geyMhIC4gISN9ICsgYiBeIHsjISAuICEjfSA9IGMgXiB7IyEgLiAhI30gJCQKIyEgZW5kICEjClxlbmR7ZG9jdW1lbnR9Cg==", "details": { "Exponents": [2,3,4,10] } }' --output pyth.pdf "http://127.0.0.1:27182/generate"
```

The result: see attached PDF
[pyth.pdf](https://github.com/raphaelreyna/latte/files/5434100/pyth.pdf)

If you want to learn more about how the templating works and which features are available, [check out the the documentation for the Go text/template package](https://golang.org/pkg/text/template/).

Let me know if this solves your issue :+1:

**Comment by maxiride** [comment]
Thank for directing me in the right way, I actually needed to range over a slice of a struct but but thanks for your example I managed to figure out the last steps! =)
