### ISSUE TITLE
Custom CLS as a registered resource - resource not found when generating

### ISSUE THREAD

**Issue by maxiride** [raphaelreyna/latte#13]
I've tried to register a custom CLS file as a resource, however when attempting to generate a document with it, I receive the error "resource with --id-- not found".

I'm unsure this is a bug, the documentation always refer to resources as files as resources to use _inside_ the document while a cls is called in the _\documentclass_ part of a .tex file.

If this is the intended behavior I'd like to explore further how to provide a custom cls otherwise it might indeed be a bug.

**Comment by raphaelreyna** [comment]
This is indeed a bug and not intended to normal behavior, thanks for pointing it out!

I'll be looking into this shortly; I know its not ideal and it might not fit your use case, but in the mean time you can use unregistered resources by sending all resources along with the template in the API call.

Hopefully I can get this fixed soon!
