### ISSUE TITLE
Can't make Pythagorean example work

### ISSUE THREAD

**Issue by janiskemper** [raphaelreyna/latte#16]
I cloned the repo and used go run to build up the server. Then I tried to reproduce your example with curl, resulting in a file that cannot be opened by a PDF viewer since it has the format "text/plain". The content of the file was the error message "invalid character '\\' looking for beginning of object key string".

Do you have an idea of what I might be doing wrong?

Another problem is that I did not manage to use Golang to properly handle the http post request (replacing curl). I tried to copy the contents of response.Body into a file using io.Copy, but it didn't work. Maybe you have some suggestions.

i am quite new to this topic, so please be gentle with me if the questions/problems are very stupid...

**Comment by raphaelreyna** [comment]
No worries regarding your questions, they're perfectly good questions!


>  The content of the file was the error message "invalid character '\' looking for beginning of object key string".

That error message makes me think its an issue with the LaTeX template being used;
LaTeX files start with `\documentclass{...}` which is an object key string, while TeX documents start with just `\`.

Try using the following command and let me know how it goes:
```
curl \
-X POST \
-H "Content-Type: application/json" \
-d '{"template":"XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo=", "details": { "a": "x", "b": "y", "c": "z" } }' \
--output pythagorean.pdf "http://localhost:27182/generate"
```

**Comment by janiskemper** [comment]
Thanks  a lot! This works. I don't really know why, but apparently
```
curl \
-X POST \
-H "Content-Type: application/json" \
-d '{"template":"XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo=", "details": { "a": "x", "b": "y", "c": "z" } }' \
--output pythagorean.pdf "http://localhost:27182/generate"
```
works, whereas 
```
curl -X POST -H "Content-Type: application/json" \
-d '{"template":"XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo=", \
"details": { "a": "x", "b": "y", "c": "z" } }' \
--output pythagorean.pdf "http://localhost:27182/generate"
```
does not. My second problem (I could also open another issue if you want) is the handling of the response in Golang. The following code leads a a strangely encoded http response which I cannot handle. Do you have any suggestions? Thanks in advance again!

```
template := "XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo="
details := map[string]string{"a": "x", "b": "y", "c": "z"}

latexRequest := LatexRequest{Template: template, Details: details}
requestBody, err := json.Marshal(latexRequest)
if err != nil {
	panic(err)
}
fmt.Println(string(requestBody))
resp, err := http.Post("http://localhost:27182/generate", "application/json", bytes.NewBuffer(requestBody))
```

**Comment by raphaelreyna** [comment]
> Thanks a lot! This works. I don't really know why, [...]  

You're welcome. 
The example thats currently up sends a TeX template (which is different from a LaTeX template) as a base64 encoded string. 
The example I gave you sends a LaTeX template as base64 instead.
LaTTe will default to handling LaTeX and not TeX if it finds a LaTeX compiler; I'm guessing it found a LaTeX installation on your machine which is why it errored out when presented with TeX instead.



> [...] apparently
> 
> ```
> curl \
> -X POST \
> -H "Content-Type: application/json" \
> -d '{"template":"XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo=", "details": { "a": "x", "b": "y", "c": "z" } }' \
> --output pythagorean.pdf "http://localhost:27182/generate"
> ```
> works, whereas
> 
> ```
> curl -X POST -H "Content-Type: application/json" \
> -d '{"template":"XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo=", \
> "details": { "a": "x", "b": "y", "c": "z" } }' \
> --output pythagorean.pdf "http://localhost:27182/generate"
> ```
> does not.

In the second example, the JSON string is being broken between the `template` and `details` fields by `\` and a newline which makes for invalid JSON. 



> My second problem (I could also open another issue if you want) is the handling of the response in Golang. The following code leads a a strangely encoded http response which I cannot handle. Do you have any suggestions? Thanks in advance again!
> 
> ```
> template := "XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo="
> details := map[string]string{"a": "x", "b": "y", "c": "z"}
> 
> latexRequest := LatexRequest{Template: template, Details: details}
> requestBody, err := json.Marshal(latexRequest)
> if err != nil {
> 	panic(err)
> }
> fmt.Println(string(requestBody))
> resp, err := http.Post("http://localhost:27182/generate", "application/json", bytes.NewBuffer(requestBody))
> ```

I wasn't able to reproduce the issue you're describing.
Heres the code I used (minimally extrapolated from yours):
```Go
package main

import "encoding/json"
import "net/http"
import "os"
import "bytes"
import "io"

type LatexRequest struct {
        Template string
        Details map[string]string
}

func main() {
        template := "XGRvY3VtZW50Y2xhc3N7YXJ0aWNsZX0KXHRpdGxle0xhVFRlIFNhbXBsZSBEb2N1bWVudH0KXGJlZ2lue2RvY3VtZW50fQpcbWFrZXRpdGxlClRoZSBQeXRoYWdvcmVhbiBUaGVvcmVtOiAKJCAjIS5hISMgXiAyICsgIyEuYiEjIF4gMiA9ICMhLmMhIyBeIDIgJApcZW5ke2RvY3VtZW50fQo="
        details := map[string]string{"a": "x", "b": "y", "c": "z"}

        latexRequest := LatexRequest{
                Template: template,
                Details: details,
        }

        requestBody, err := json.Marshal(latexRequest)
        if err != nil {
                panic(err)
        }

        resp, err := http.Post(
                "http://localhost:27182/generate",
                "application/json",
                bytes.NewBuffer(requestBody),
        )
        if err != nil {
                panic(err)
        }

        if resp.StatusCode != http.StatusOK {
                panic(resp.Status)
        }

        defer resp.Body.Close()
        io.Copy(os.Stdout, resp.Body)
}
```
I get the correct PDF when I run:
```bash
go run main.go >> test.pdf
```
Perhaps posting your definition of `LatexRequest` might help?

**Comment by janiskemper** [comment]
Thank you very much! Your code was indeed exactly the same as I used. Knowing this, I was able to find the "mistake" though. I didn't know that VS Code shows PDFs with another encoding which is not readable for humans. It worked the whole time, I was just too stupid to see it :D
