### ISSUE TITLE
User should be able to choose delimiters

### ISSUE THREAD

**Issue by raphaelreyna** [raphaelreyna/latte#3]
Currently, LaTTe only accepts templates using #! and !# as the left and right delimiters respectively.

**Comment by Maxiride** [comment]
>LaTTe only accepts templates using #! and !#

Is there a particular reason why this choice was made or it boils down to flavour and compatibility with LaTeX commands\special characters etc?

**Comment by raphaelreyna** [comment]
> > LaTTe only accepts templates using #! and !#
> 
> Is there a particular reason why this choice was made or it boils down to flavour and compatibility with LaTeX commands\special characters etc?

The default for Go's `text/template` is to use `{{` and `}}`; these immediately cause issues with most .tex files. The choice to use `#!` and `!#` came about because they were the first delimiters I thought of that wouldn't cause issues with the .tex files I was trying to process.

**Comment by raphaelreyna** [comment]
I've now added support for custom delimiters (still defaults to `#!` and `!#`).
Custom delimiters can be passed in with the JSON body for requests to generate a new PDF:
```
{
	"template": "BASE_64_ENCODED_STRING",
	"resources": {
		"FILE_NAME": "BASE_64_ENCODED_STRING"
		},
	"details": { SOME_OBJECT_DESCRIBING_YOUR_SUBSTITUTIONS },
	"delimiters": { "left": "LEFT_DELIMITER", "right": "RIGHT_DELIMITER" }
}
```
