### ISSUE TITLE
Default self-contained database? 

### ISSUE THREAD

**Issue by Xeoncross** [raphaelreyna/latte#6]
The [DB interface](https://github.com/raphaelreyna/latte/blob/bc7c8986d0/internal/server/database.go) looks perfect for an embedded key/value store like [badger](https://github.com/dgraph-io/badger) or [bbolt](https://github.com/etcd-io/bbolt). Any plans to make latte self-contained with a default on-disk, memory-only, or embedded database implementation?

Some pseudocode:

```go
type MemoryDB struct {
	docs map[string]interface{}
}


// Store should be capable of storing a given []byte or contents of an io.ReadCloser
func (db *MemoryDB) Store(ctx context.Context, uid string, i interface{}) error {
	db.docs[uid] = i
	return nil
}

// Fetch should return either a []byte, or io.ReadCloser.
// If the requested resource could not be found, error should be of type NotFoundError
func (db *MemoryDB) Fetch(ctx context.Context, uid string) (interface{}, error) {
	if v, ok := db.docs[uid]; ok {
		return v, nil
	}
	return nil, NotFoundError{}
}

// Ping should check if the databases is reachable, if return error should be nil and non-nil otherwise.
func (db *MemoryDB) Ping(ctx context.Context) error {
	return nil
}
```

**Comment by raphaelreyna** [comment]
Hi, thanks for your interest in LaTTe!
By default LaTTe always stores and retrieves files from the local disk first before checking the database/store (if compiled with database support); because of this, I'm having a hard time understanding wanting something like an embedded database.

I'm totally open to being shown an example use case, or hearing more about it though!

**Comment by Xeoncross** [comment]
Ah, I missed that then. I wasn't aware it already defaulted to local disk storage. That kind of solves this as I was interested in short-term containers that I could HTTP send a bunch of JSON documents too, render a report, then remove.

**Comment by raphaelreyna** [comment]
> Ah, I missed that then. I wasn't aware it already defaulted to local disk storage. That kind of solves this as I was interested in short-term containers that I could HTTP send a bunch of JSON documents too, render a report, then remove.

Glad to hear that solves the issue for you!
